spring:
  application:
    name: xlendzuser
  datasource:
    url: jdbc:postgresql://localhost:5432/xlendzuser
    username: postgres
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "technicalyusaf@gmail.com"
    password: "pebs afgn lwgw rfkg"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      from: "technicalyusaf@gmail.com"

xlendz:
  confirmation:
    url: "http://localhost:8080"

#    /*
#    spring:
#      profiles: dev
#      datasource:
#        url: jdbc:h2:mem:devdb
#        username: dev
#        password: devpass
#
#    ---
#    spring:
#      profiles: prod
#      datasource:
#        url: jdbc:mysql://prod-db:3306/proddb
#        username: prod
#        password: prodpass